# 기본
spring.profiles.active=dev
spring.thymeleaf.cache=false

# DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 매알
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 프로젝트 커스텀 값
spring.config.import=application-secret.properties